### ISSUE TITLE
Confused by some Random Errors 

### ISSUE THREAD

**Issue by samkazmi** [markrjr/Salut#2]
Hi Mark..
Very Nice Library great work ... but i'm working on Wifi Direct for the first time so i'm not sure how to use your library... can you please create sample projects showing its basic usage and difference between Host and Client...

 it is giving me error when i use startNetworkService function to create a host
Failed to create __signaldispalyservice : Error Code: 0
and when i create an instance it gives this error

06-29 17:47:29.377: E/Salut(21732): Failed to use standard port, another will be used instead.
06-29 17:47:29.377: E/Salut(21732): Failed to get a random port, Salut will not work correctly.
06-29 17:47:29.377: E/Salut(21732): Failed to use standard port, another will be used instead.
06-29 17:47:29.377: E/Salut(21732): Failed to get a random port, __childdisplayservice will not work correctly.

**Comment by neatorobito** [comment]
I'm looking into this. What device are you testing on and what port are you trying to use for your service?

**Comment by samkazmi** [comment]
this is my code for Host Activity I'm Using Samsung galaxy s4 and a asus tablet android version 4.2.2

public class MainActivity extends AppCompatActivity {
    public static SalutDataReceiver dataReceiver;
    public static SalutServiceData serviceData;
    public static Salut network;

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
    MainFragment mainFragment = new MainFragment();
    ft.replace(R.id.fMainActivityFragmentPlaceHolder, mainFragment)
            .commit();

    dataReceiver = new SalutDataReceiver(this, new SalutDataCallback() {

        @Override
        public void onDataReceived(Object data) {
            // TODO Auto-generated method stub

        }
    });

    serviceData = new SalutServiceData("_signaldispalyservice", 5062,
            "parent");
    network = new Salut(dataReceiver, serviceData, new SalutCallback() {
        @Override
        public void call() {
            // wiFiFailureDiag.show();
            // OR
            Log.e("Main",
                    "Sorry, but this device does not support WiFi Direct.");
        }
    });
    Log.e("Main",
            "Host: "+ network.isRunningAsHost);
}

@Override
protected void onDestroy() {
    super.onDestroy();
    network.unregisterClient(new SalutCallback() {

        @Override
        public void call() {

        }
    });
}
```

}

**Comment by neatorobito** [comment]
I've pushed a new build with some minor bug fixes, so you'll have to update your build.gradle file's compile dependencies to:

```
    compile 'com.github.markrjr:Salut:v0.4.3'
```

Also, try using a port greater than 10000.

**Comment by samkazmi** [comment]
I'm Using Eclipse ... I've to download it....
Thanks for the update i'll let you know...

**Comment by samkazmi** [comment]
Hi Mark Sorry for the inconvenience but this is not working for me..
here is my code and log.... may be i'm missing something.. 

import com.pantera.fragments.MainFragment;
import com.peak.salut.Salut;
import com.peak.salut.SalutDataReceiver;
import com.peak.salut.SalutServiceData;
import com.peak.salut.Callbacks.SalutCallback;
import com.peak.salut.Callbacks.SalutDataCallback;
import android.os.Bundle;
import android.support.v4.app.FragmentTransaction;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;

public class MainActivity extends AppCompatActivity {
    public static SalutDataReceiver dataReceiver;
    public static SalutServiceData serviceData;
    public static Salut network;
    SalutDataCallback callback;

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
    MainFragment mainFragment = new MainFragment();
    ft.replace(R.id.fMainActivityFragmentPlaceHolder, mainFragment)
            .commit();
    SalutDataCallback callback = new SalutDataCallback() {

        @Override
        public void onDataReceived(Object data) {
            //Data Is Received

        }
    };
    dataReceiver = new SalutDataReceiver(this, callback);

    serviceData = new SalutServiceData("_signaldispalyservice", 60606,
            "parent");
    network = new Salut(dataReceiver, serviceData, new SalutCallback() {
        @Override
        public void call() {
            // wiFiFailureDiag.show();
            // OR
            Log.e("Main",
                    "Sorry, but this device does not support WiFi Direct.");
        }
    });
    Log.e("Main", "Host: " + network.isRunningAsHost);
}

@Override
protected void onDestroy() {
    super.onDestroy();
    network.stopNetworkService(false);
    network.unregisterClient(new SalutCallback() {

        @Override
        public void call() {
            // success
        }
    }, new SalutCallback() {

        @Override
        public void call() {
            // failure

        }
    }, false);
}
```

}

Its log: 

06-29 20:37:52.404: E/Salut(28268): Failed to use standard port, another will be used instead.
06-29 20:37:52.404: E/Salut(28268): Failed to get a random port, Salut will not work correctly.
06-29 20:37:52.404: E/Salut(28268): Failed to use standard port, another will be used instead.
06-29 20:37:52.404: E/Salut(28268): Failed to get a random port, __signaldispalyservice will not work correctly.
06-29 20:37:52.404: E/Main(28268): Host: false

the fragment where i try to start network service in Onclick 

import com.pantera.signaldisplay.MainActivity;
import com.pantera.signaldisplay.R;
import com.peak.salut.SalutDevice;
import com.peak.salut.Callbacks.SalutCallback;
import com.peak.salut.Callbacks.SalutDeviceCallback;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;

public class LinkFragment extends Fragment implements OnClickListener {

```
View view;
ImageView ivFindDevices;

@Override
@Nullable
public View onCreateView(LayoutInflater inflater,
        @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
    view = inflater.inflate(R.layout.link_fragment, container, false);
    ivFindDevices = (ImageView) view
            .findViewById(R.id.ivLinkFragment_FindChildDevices);
    ivFindDevices.setOnClickListener(this);

    return view;
}

@Override
public void onClick(View v) {
    MainActivity.network.startNetworkService(new SalutDeviceCallback() {
        @Override
        public void call(SalutDevice device) {
            Log.d("HOST", device.readableName + " has connected!");
        }

    }, new SalutCallback() {

        @Override
        public void call() {
            Log.d("HOST", "Success");   
        }
    }, new SalutCallback() {

        @Override
        public void call() {
            Log.d("HOST", "Failure");   
        }
    });
    Log.e("Main", "Host: " + MainActivity.network.isRunningAsHost);
}
```

}

its log: 

06-29 20:30:52.291: D/Salut(28268): Starting __signaldispalyservice Transport Protocol __signaldispalyservice._tcp
06-29 20:30:52.313: E/Main(28268): Host: false
06-29 20:30:52.313: V/Salut(28268): Not connected to another device.
06-29 20:30:52.316: D/WifiP2pManager(28268): Ignored { what=139313 when=-8ms target=Handler (android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler) {4196dd70} }
06-29 20:30:52.320: D/WifiP2pManager(28268): Ignored { what=139313 when=-10ms target=Handler (android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler) {417a9e08} }
06-29 20:30:52.321: E/Salut(28268): Failed to create __signaldispalyservice : Error Code: 0
06-29 20:30:52.322: D/HOST(28268): Failure
06-29 20:30:52.322: D/WifiP2pManager(28268): Ignored { what=139313 when=-11ms target=Handler (android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler) {4196dd70} }
06-29 20:30:52.326: D/WifiP2pManager(28268): Ignored { what=139313 when=-12ms target=Handler (android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler) {417a9e08} }
06-29 20:30:52.327: D/WifiP2pManager(28268): Ignored { what=139313 when=-17ms target=Handler (android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler) {4182aba0} }
06-29 20:30:52.328: V/Salut(28268): Service discovery request acknowledged.
06-29 20:30:52.332: D/Salut(28268): Service discovery initiated.

when MainActiviy is Destroyed...

06-29 20:29:21.345: D/Salut(28268): Network service is not running.
06-29 20:29:21.400: D/Salut(28268): Attempted to unregister, but not connected to group. The remote service may already have shutdown.
06-29 20:29:21.400: E/Salut(28268): Failed to close one or more sockets. Perhaps they were already closed or null.
06-29 20:29:21.400: E/Salut(28268): Failed to close one or more sockets. Perhaps they were already closed or null?

**Comment by neatorobito** [comment]
I've figured it out!

So before I get to the actual issue, a few things. In your code, you recreate the `SalutDataCallback`. You have one declared for your class and then you declare another in `onCreate.`

You can also remove the underscore from your service name, I forgot to update the readme, but the framework will put that there for you.

Now on to the issue, you actually need the following in your AndroidManifest.xml.

```
    <uses-permission android:name="android.permission.INTERNET" />
```

Turns out that you can't actually open ports on Android without the internet permission.

Thanks for opening that issue, otherwise we both would have never found out about this. I've updated the readme accordingly.

**Comment by samkazmi** [comment]
So For So Good... Thanks The Service is Running but i've another problem..
when i start a networkService like this after initiating the object

network.startNetworkService(new SalutDeviceCallback() {
        @Override
        public void call(SalutDevice device) {
            Log.d("HOST", device.readableName + " has connected!");
        }

```
}, new SalutCallback() {

    @Override
    public void call() {
        Log.d("HOST", "Success");   
    }
}, new SalutCallback() {

    @Override
    public void call() {
        Log.d("HOST", "Failure");   
    }
});
```

it says failed to create _signaldisplayservice

06-30 14:20:43.316: D/Salut(11983): Starting _signaldispalyservice Transport Protocol _signaldispalyservice._tcp
06-30 14:20:43.341: E/Main(11983): Host: false
06-30 14:20:43.341: D/WifiP2pManager(11983): Ignored { what=139313 when=-11ms target=Handler (android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler) {417a0e48} }
06-30 14:20:43.341: E/Salut(11983): Failed to create _signaldispalyservice : Error Code: 0
06-30 14:20:43.341: D/HOST(11983): Failure
06-30 14:20:43.342: D/WifiP2pManager(11983): Ignored { what=139313 when=-8ms target=Handler (android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler) {417a0e48} }
06-30 14:20:43.344: V/Salut(11983): Service discovery request acknowledged.
06-30 14:20:43.344: D/Salut(11983): Service discovery initiated.

And when i try to discover from another device it only shows the service running not the device 

network.discoverNetworkServicesWithTimeout(new SalutCallback() {
            @Override
            public void call() {
                textView.setText("Look at all these devices! "
                        + network.foundDevices.toString());
                Log.d("",
                        "Look at all these devices! "
                                + network.foundDevices.toString());
            }
        }, new SalutCallback() {
            @Override
            public void call() {
                textView.setText("Bummer, we didn't find anyone. ");
                Log.d("", "Bummer, we didn't find anyone. ");
            }
        }, 25000);

06-30 14:11:46.493: V/Salut(13843): Not connected to another device.
06-30 14:11:46.498: V/Salut(13843): Service discovery request acknowledged.
06-30 14:11:46.643: D/OpenGLRenderer(13843): Enabling debug mode 0
06-30 14:11:46.648: D/Salut(13843): Service discovery initiated.
06-30 14:11:49.128: D/Salut(13843): Found myparentinstance-1391081894 _signaldispalyservice._tcp.local.
06-30 14:11:49.128: D/Salut(13843): Found parent-1391081894 __signaldispalyservice._tcp.local.
06-30 14:11:49.128: D/Salut(13843): Found whatever-1391081894 __superawesomeservice._tcp.local.
06-30 14:12:11.503: D/(13843): Bummer, we didn't find anyone. 
06-30 14:12:11.593: V/Salut(13843): Successfully removed service discovery request.

and please clear one more thing, how to create a host and how to connect the devices to the host?

**Comment by samkazmi** [comment]
Can You please make a sample for your library?

**Comment by neatorobito** [comment]
Perhaps sometime in the future. For now, however, the readme should definitely suffice as material to answer most of your questions, particularly even the ones you've just asked, and when that fails there is looking at the actual code for the library itself.

**Comment by loulansuiye** [comment]
I’v meet the similar problem as the following description
10-19 11:09:07.871 7997-7997/ D/WifiP2pManager: Ignored { when=0 what=139313 target=android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler }

**Comment by loulansuiye** [comment]
I use the the service discovery via wifi direct to broadcast data to device nearby in circulation mode
