### ISSUE TITLE
Create Salut instance in Service

### ISSUE THREAD

**Issue by svarogSLASHc** [markrjr/Salut#3]
Hi! 
How can I create Salut instance in Service for background scanning?
SalutDataReceiver require Activity instance.
Thank you

**Comment by neatorobito** [comment]
SalutDataReceiver takes two arguments,(Activity activity, SalutDataCallback dataCallback). 

The activity argument allows the framework to automatically declare and destroy broadcast receivers tied to the passed in activity. It also lets the framework use the activity's runOnUIThread method to run callbacks on, which the Service class does not have. 

You can still receive data within a service, you can simply have your service implement the SalutDataCallback and then pass the service as the second argument.

It looks like it's possible to use a service instead of an activity for the first argument, but it'll require a few changes that I'll have to push. [Also, here's a sample project if it helps.](http://d.pr/f/10k4G)

**Comment by svarogSLASHc** [comment]
Thank you for fast response. But I need to use host and client at the same time on Service independent of UI

**Comment by svarogSLASHc** [comment]
The question is, can I discoverNetworkServices and startNetworkService at the same time? I would like every device discover nearby and work like NetworkService

**Comment by neatorobito** [comment]
This is not currently possible because startNetworkService internally calls discoverNetworkService. It simply does not setup callbacks.

**Comment by arniesaha** [comment]
Hey! Great Library! I'm trying to use this in a service too. While I understand you've marked this as an enhancement, the link to a sample project you've mentioned in the earlier comments is dead at the moment. Could you maybe put that up again? http://d.pr/f/10k4G

Thanks in advance!
Arnab

**Comment by neatorobito** [comment]
I apologize for the late response, I hope I'm not too late.
I had to recreate the  sample project and I haven't had a ton of time lately. I'll also post a permanent link on the readme.
[Here's a link!](http://d.pr/f/17NrP)

**Comment by arniesaha** [comment]
Thanks! I've edited the library to be used in a service. Which works fine. But, I'm trying to discover advertisement from peers which could be dynamic in nature, i.e. the advertisement changes depending on the app use. While, the broadcast receiver gets the peer state change more reliably. The dnssdtxtrecord doesn't always gets listened to. I try to work-around by forcing the wifi state to re-enabled (stop/start the wifi) which helps to get the advertisement again. But, not a very reliable way, as it cycles through the process of re-enabling wifi until the advertisement is received for a peer. 

But, what I've noticed is some of the earlier advertisements are pooled and keep showing even when the advertising device has stopped advertising, and the TXT Listeners do not attach and at times. Which causes a WifiP2pManager ignored warning while adding both the local service as well as the service discovery request. Hence, the listener doesn't get the advertisement at times, while keeps getting advertisements at times when even Wifi is disabled.

Any ideas of how to go about improving this overall discovery process?

**Comment by neatorobito** [comment]
[You could use the DNSSDServiceResponseListener class.](http://developer.android.com/reference/android/net/wifi/p2p/WifiP2pManager.DnsSdServiceResponseListener.html) 

It's in the Salut code here, but it fires no callbacks.

```
    private void setupDNSResponders(final SalutCallback onDeviceFound, final boolean callContinously)
    {
         /*Here, we register a listener for when services are actually found. The WiFi P2P specification notes that we need two types of
         *listeners, one for a DNS service and one for a TXT record. The DNS service listener is invoked whenever a service is found, regardless
         *of whether or not it is yours. To that determine if it is, we must compare our service name with the service name. If it is our service,
         * we simply log.*/

        WifiP2pManager.DnsSdServiceResponseListener serviceListener = new WifiP2pManager.DnsSdServiceResponseListener() {
            @Override
            public void onDnsSdServiceAvailable(String instanceName, String serviceNameAndTP, WifiP2pDevice sourceDevice) {

                Log.d(TAG, "Found " + instanceName +  " " + serviceNameAndTP);

            }
        };
```

There is another way to use WiFi Direct in Android, and that it is the discoverPeers method, which may be more reliable. It doesn't use DNS txt records or services, it simply scans for WiFi Direct capable devices from what I understand. This is not used at all in Salut.

http://developer.android.com/training/connect-devices-wirelessly/wifi-direct.html

Look there, around the "Initiate Peer Discovery" section. Much like everything for WiFi Direct under Android though, it's probably not very well documented.

**Comment by derick31** [comment]
Hello, I hope it is not too late, but I am trying to use this awesome library on a Service. But I can't seem to do it and the link above is already dead. Thank you.
