### ISSUE TITLE
In sendMessage, device has no serviceAddress or servicePort.

### ISSUE THREAD

**Issue by VitorFontenelle** [markrjr/Salut#35]
Hello. First of all, I thank you and appreciate you for your work.
I am trying to send a simple text message from the Client to the Host, but I can't seen to figure it out how. 
When I call startNetworkService, the callback saying it's connected is never called, but the devices seem to be conected by WiFi Direct. When I try to use sendMessage method I get the error callback, and the log tells me it's because the device have no serviceAddress or servicePort.
I am using version 0.5.1, but I have tried to downgrade to 0.5.0 and 0.4.9, and for some reason, in these versions the Client don't even discover the Host...
Can anyone point out what am I doing wrong? Or have an working project, because I really only need to send Strings from one device to another. Pasting the code below:

`
public class MainActivity extends AppCompatActivity implements SalutDataCallback, View.OnClickListener{

    public static final String TAG = "SalutTestApp";
    public SalutDataReceiver dataReceiver;
    public SalutServiceData serviceData;
    public Salut network;
    public Button hostingBtn;
    public Button discoverBtn;
    public Button messageBtn;
    public Button registerBtn;
    SalutDataCallback callback;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        hostingBtn = (Button) findViewById(R.id.hosting_button);
        discoverBtn = (Button) findViewById(R.id.discover_services);
        messageBtn = (Button) findViewById(R.id.send_message);
        registerBtn = (Button) findViewById(R.id.register);

        hostingBtn.setOnClickListener(this);
        discoverBtn.setOnClickListener(this);
        messageBtn.setOnClickListener(this);
        registerBtn.setOnClickListener(this);

        /*Create a data receiver object that will bind the callback
        with some instantiated object from our app. */
        dataReceiver = new SalutDataReceiver(this, this);

        /*Populate the details for our awesome service. */
        serviceData = new SalutServiceData("testAwesomeService", 60606,
                "HOST");

        /*Create an instance of the Salut class, with all of the necessary data from before.
        * We'll also provide a callback just in case a device doesn't support WiFi Direct, which
        * Salut will tell us about before we start trying to use methods.*/
        network = new Salut(dataReceiver, serviceData, new SalutCallback() {
            @Override
            public void call() {
                // wiFiFailureDiag.show();
                // OR
                Log.e(TAG, "Sorry, but this device does not support WiFi Direct.");
            }
        }) {
            @Override
            public String serialize(Object o) {
                return null;
            }
        };
    }

    @Override
    public void onClick(View v) {

        if(!Salut.isWiFiEnabled(getApplicationContext()))
        {
            Toast.makeText(getApplicationContext(), "Please enable WiFi first.", Toast.LENGTH_SHORT).show();
            return;
        }

        if(v.getId() == R.id.hosting_button)
        {
            setupNetwork();
        }
        else if(v.getId() == R.id.discover_services)
        {
            discoverServices();
        }
        else if(v.getId() == R.id.send_message)
        {
            sendMessage();
        }
        else if(v.getId() == R.id.register)
        {
            registerDevice();
        }
    }

    private void setupNetwork()
    {
        if(!network.isRunningAsHost)
        {
            network.startNetworkService(new SalutDeviceCallback() {
                @Override
                public void call(SalutDevice salutDevice) {
                    Toast.makeText(getApplicationContext(), "Device: " + salutDevice.instanceName + " connected.", Toast.LENGTH_SHORT).show();
                }
            });

            hostingBtn.setText("Stop Service");
            discoverBtn.setAlpha(0.5f);
            discoverBtn.setClickable(false);
            network.isRunningAsHost = true;
        }
        else
        {
            network.stopNetworkService(false);
            hostingBtn.setText("Start Service");
            discoverBtn.setAlpha(1f);
            discoverBtn.setClickable(true);
            network.isRunningAsHost = false;
        }
    }

    private void discoverServices()
    {
        if(!network.isRunningAsHost && !network.isDiscovering)
        {
            network.discoverNetworkServices(new SalutCallback() {
                @Override
                public void call() {
                    Toast.makeText(getApplicationContext(), "Device: " + network.foundDevices.get(0).instanceName + " found.", Toast.LENGTH_SHORT).show();
                }
            }, true);
            discoverBtn.setText("Stop Discovery");
            hostingBtn.setAlpha(0.5f);
            hostingBtn.setClickable(false);
        }
        else
        {
            network.stopServiceDiscovery(true);
            discoverBtn.setText("Discover Services");
            hostingBtn.setAlpha(1f);
            hostingBtn.setClickable(false);
        }
    }

    private void registerDevice(){
        network.registerWithHost(network.foundDevices.get(0), new SalutCallback() {
            @Override
            public void call() { //Salut Device Possible Host
                Log.d(TAG, "We're now registered.");
            }
        }, new SalutCallback() {
            @Override
            public void call() {
                Log.d(TAG, "We failed to register.");
            }
        });
    }

    private void sendMessage(){
        Salut salAux= network;
        Message myMessage = new Message();
        myMessage.description = "See you on the other side!";

        //network.sendToAllDevices(myMessage, new SalutCallback() {
        //    @Override
        //    public void call() {
        //        Log.e(TAG, "Oh no! The data failed to send.");
        //        Toast.makeText(getApplicationContext(), "Oh no! The data failed to send.", Toast.LENGTH_SHORT).show();
        //    }
        //});

        network.sendToDevice(network.foundDevices.get(0), myMessage, new SalutCallback() {
            @Override
            public void call() {
                Log.e(TAG, "Oh no! The data failed to send.");
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        //getMenuInflater().inflate(R.menu.menu_base, menu); TODO Menu Não funciona
        return true;
    }

    /*Create a callback where we will actually process the data.*/
    @Override
    public void onDataReceived(Object data) {
        //Data Is Received
        Log.d(TAG, "Received network data.");
        try
        {
            //TODO Se algo quebrar, provavelmente foi aqui.
            Message newMessage = LoganSquare.parse(data.toString(), Message.class);
            Log.d(TAG, newMessage.description);  //See you on the other side!
            Toast.makeText(getApplicationContext(), newMessage.description, Toast.LENGTH_SHORT).show();
            //Do other stuff with data.
        }
        catch (IOException ex)
        {
            Log.e(TAG, "Failed to parse network data.");
        }
    }

    @Override
    public void onDestroy() {
        super.onDestroy();

        if(network.isRunningAsHost)
            network.stopNetworkService(true);
        else
            network.unregisterClient(true);
    }
}
`

Thank you previously for your help.

**Comment by VitorFontenelle** [comment]
Actually, when I downgraded to 0.4.9, I realized after a few more tests that one of the devices does not work as host, but the other one does, and the error was solved. Now I'm having problems with Logansquare, saying that the JsonObject could not be mapped, but I guess it has nothing to do with Salut, so you can deal this as solved.

**Comment by miroslavign** [comment]
@MaxGoiabinha 
I have the same issue using latest code from master/head.
Have you had any luck in resolving this one ?
Do you now have at least a minimally working demo app ?

**Comment by VitorFontenelle** [comment]
Sorry for the late reply, @miroslavign .
As I said in the comment above, when I downgraded to version 0.4.9 it did work, but yes, I do have an working demo app. I can e-mail it to you, but you don't have a public e-mail address. Send a "Hi" to my e-mail if you still need any help.
