### ISSUE TITLE
Data Sending Error

### ISSUE THREAD

**Issue by wyounglee** [markrjr/Salut#4]
When I try to send any data, I got sending error.
What's wrong?

@ If you have any sample code, please share it with me.

Many thanks.

..............
                if(network.isRunningAsHost) {
                    network.sendToAllDevices("This is test data", new SalutCallback() {
                        @Override
                        public void call() {
                            Log.e(TAG, "Oh no! The data failed to send.");
                        }
                    });
.......................

01-04 18:16:08.937 13864-15985/com.innopia.fx3drvier2th D/Salut: Connected, transferring data...
01-04 18:16:08.937 13864-15985/com.innopia.fx3drvier2th D/Salut: An error occurred while sending data to a device.
01-04 18:16:08.937 13864-15985/com.innopia.fx3drvier2th E/SalutTestApp: Oh no! The data failed to send.
01-04 18:16:08.947 13864-15985/com.innopia.fx3drvier2th W/System.err: com.bluelinelabs.logansquare.NoSuchMapperException: Class java.lang.String could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
01-04 18:16:08.947 13864-15985/com.innopia.fx3drvier2th W/System.err:     at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:171)
01-04 18:16:08.947 13864-15985/com.innopia.fx3drvier2th W/System.err:     at com.bluelinelabs.logansquare.LoganSquare.serialize(LoganSquare.java:100)
01-04 18:16:08.947 13864-15985/com.innopia.fx3drvier2th W/System.err:     at com.peak.salut.BackgroundDataSendJob.doOnBackground(BackgroundDataSendJob.java:49)
01-04 18:16:08.947 13864-15985/com.innopia.fx3drvier2th W/System.err:     at com.arasthel.asyncjob.AsyncJob$2.run(AsyncJob.java:59)
01-04 18:16:08.947 13864-15985/com.innopia.fx3drvier2th W/System.err:     at java.lang.Thread.run(Thread.java:841)
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err: Caused by: java.lang.ClassNotFoundException: java.lang.String$$JsonObjectMapper
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err:     at java.lang.Class.classForName(Native Method)
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err:     at java.lang.Class.forName(Class.java:251)
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err:     at java.lang.Class.forName(Class.java:216)
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err:     at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:167)
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err:   ... 4 more
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err: Caused by: java.lang.NoClassDefFoundError: java/lang/String$$JsonObjectMapper
01-04 18:16:08.957 13864-15985/com.innopia.fx3drvier2th W/System.err:   ... 8 more
01-04 18:16:08.967 13864-15985/com.innopia.fx3drvier2th W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.String$$JsonObjectMapper" on path: DexPathList[[zip file "/data/app/com.innopia.fx3drvier2th-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.innopia.fx3drvier2th-1, /vendor/lib, /system/lib]]
01-04 18:16:08.967 13864-15985/com.innopia.fx3drvier2th W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-04 18:16:08.967 13864-15985/com.innopia.fx3drvier2th W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
01-04 18:16:08.967 13864-15985/com.innopia.fx3drvier2th W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
01-04 18:16:08.967 13864-15985/com.innopia.fx3drvier2th W/System.err:   ... 8 more

**Comment by wyounglee** [comment]
Another Log is:

01-04 19:20:55.389 31893-1172/ac.kr.sogang.cmuitmd D/Salut: Connected, transferring data...
01-04 19:20:55.389 31893-1172/ac.kr.sogang.cmuitmd W/dalvikvm: dvmFindClassByName rejecting '[B$$JsonObjectMapper'
01-04 19:20:55.389 31893-1172/ac.kr.sogang.cmuitmd D/Salut: An error occurred while sending data to a device.
01-04 19:20:55.389 31893-1172/ac.kr.sogang.cmuitmd E/SalutTestApp: Sending Failure!!!
01-04 19:20:55.389 31893-1172/ac.kr.sogang.cmuitmd W/System.err: com.bluelinelabs.logansquare.NoSuchMapperException: Class byte[] could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
01-04 19:20:55.399 31893-1172/ac.kr.sogang.cmuitmd W/System.err:     at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:304)
01-04 19:20:55.399 31893-1172/ac.kr.sogang.cmuitmd W/System.err:     at com.bluelinelabs.logansquare.LoganSquare.serialize(LoganSquare.java:149)
01-04 19:20:55.399 31893-1172/ac.kr.sogang.cmuitmd W/System.err:     at com.peak.salut.BackgroundDataSendJob.doOnBackground(BackgroundDataSendJob.java:49)
01-04 19:20:55.399 31893-1172/ac.kr.sogang.cmuitmd W/System.err:     at com.arasthel.asyncjob.AsyncJob$2.run(AsyncJob.java:59)
01-04 19:20:55.399 31893-1172/ac.kr.sogang.cmuitmd W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by neatorobito** [comment]
LoganSquare, which is the library that is responsible for serializing data within the library will not actually allow the sending of straight strings back and forth. You'll have to create an object wrapper.

Make sure you've added LoganSquare as a dependency to your app.

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
apply plugin: 'com.neenbedankt.android-apt'

dependencies {
    apt 'com.bluelinelabs:logansquare-compiler:1.3.4'
    compile 'com.bluelinelabs:logansquare:1.3.4'
}
```

Then, create a simple wrapper object to send back and forth.

```
@JsonObject
public class Message{

    /*
     * Annotate a field that you want sent with the @JsonField marker.
     */
    @JsonField
    public String description;

    /*
     * Note that since this field isn't annotated as a
     * @JsonField, LoganSquare will ignore it when parsing
     * and serializing this class.
     */
    public int nonJsonField;
}
```

So that when you send data, it looks like this.

```
Message myMessage = new Message();
network.sendToHost(myMessage...)
```

Here is a sample activity.
https://gist.github.com/markrjr/0519268f69a5823da17b

**Comment by wyounglee** [comment]
Thanks your answer. Now, data sending is okay.
However, I got a compile error in "onDataReceived"
Could you advice me again?
......................
    @Override
    public void onDataReceived(Object data) {
        Log.d(TAG, "Received network data.");
        try
        {
            JasonObjectData mydata = LoganSquare.parse((JasonObjectData)data, JasonObjectData.class);
            Log.d(TAG, myData.sendingData);
            // Do other stuff with data.
        }
        catch (IOException ex)
        {
            Log.e(TAG, "Failed to parse network data.");
        }
    }
..........................
Error:(222, 49) error: no suitable method found for parse(JasonObjectData,Class<JasonObjectData>)
method LoganSquare.<E#1>parse(String,ParameterizedType<E#1>) is not applicable
(no instance(s) of type variable(s) E#1 exist so that argument type JasonObjectData conforms to formal parameter type String)
method LoganSquare.<E#2>parse(InputStream,ParameterizedType<E#2>) is not applicable
(no instance(s) of type variable(s) E#2 exist so that argument type JasonObjectData conforms to formal parameter type InputStream)
method LoganSquare.<E#3>parse(String,Class<E#3>) is not applicable
(no instance(s) of type variable(s) E#3 exist so that argument type JasonObjectData conforms to formal parameter type String)
method LoganSquare.<E#4>parse(InputStream,Class<E#4>) is not applicable
(no instance(s) of type variable(s) E#4 exist so that argument type JasonObjectData conforms to formal parameter type InputStream)
where E#1,E#2,E#3,E#4 are type-variables:
E#1 extends Object declared in method <E#1>parse(String,ParameterizedType<E#1>)
E#2 extends Object declared in method <E#2>parse(InputStream,ParameterizedType<E#2>)
E#3 extends Object declared in method <E#3>parse(String,Class<E#3>)
E#4 extends Object declared in method <E#4>parse(InputStream,Class<E#4>)
.......................................

**Comment by recker115** [comment]
Gradle build error :- 

Cause: android-apt plugin is incompatible with the Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.

So, for the dependencies part ?
