### ISSUE TITLE
Wifi P2P Group Details

### ISSUE THREAD

**Issue by hjoshi123** [markrjr/Salut#41]
Can I get info of the WiFi P2p group created which includes SSID and passphrase?

**Comment by neatorobito** [comment]
Yup, you'll need to fork and likely add a public field to the `Salut` instance though. It depends on how you want to access the information.

Perhaps add a field called `currentGroup` and set it to the `group` object passed into the [onGroupInfoAvailable](https://github.com/incognitorobito/Salut/blob/master/library/src/main/java/com/peak/salut/Salut.java#L185) callback.

Then you can use `currentGroup.getNetworkName()` and other functions as described [here](https://developer.android.com/reference/android/net/wifi/p2p/WifiP2pGroup.html#getNetworkName()).

**Comment by hjoshi123** [comment]
Hey I got another error.. I am working on kotlin.. I am receiving the following error.. @incognitorobito 
![Screenshot 2019-03-12 at 13 37 26](https://user-images.githubusercontent.com/11522166/54177103-0df9c280-44cc-11e9-850b-b041d1233d24.png)

Could you check this out?
