### ISSUE TITLE
Wifi Not connecting

### ISSUE THREAD

**Issue by hjoshi123** [markrjr/Salut#42]
I got the following issue. My devices are connected to WiFi Direct through Salut. When I manually try to connect to the WiFi Direct SSID (using Group Details) its connecting and disconnecting. I have no idea whether this is WiFi Direct or Salut. Please let me know regarding this.

**Comment by neatorobito** [comment]
So the device authenticates with the WiFi Direct group correctly? Are you requesting the group password as the owner? I've never done it that particular way, but I'm happy to try and help.

**Comment by hjoshi123** [comment]
Yeah it shows the message that the device is connected but when I try to manually connect with the SSID created using the password in logs.. Its not connecting.. I had done this using WiFi Direct APIs and it had connected. So I think there is some problem with Salut?
Btw I am getting the SSID and passphrase as the group owner.

**Comment by neatorobito** [comment]
Possibly. Is there something different you did when setting up the network using the other APIs versus what Salut does? Maybe there's an extra option to pass.

**Comment by hjoshi123** [comment]
I used the official API as far as I remember. Created a group and then manually connected using the password that I got. Everything looks the same but its not happening.

**Comment by neatorobito** [comment]
After a little big of digging, I'm not particularly sure. I am not as familiar with the WiFi P2P stack in Android as I used to be.

**Comment by hjoshi123** [comment]
Hey I had a question @incognitorobito .. How can I run a timer between the host and client? If you could tell me a way it would be helpful.. Sending messages will certainly introduce the lag in timer.
