### ISSUE TITLE
How can SalutDevice be uniquely identified?

### ISSUE THREAD

**Issue by s0nerik** [markrjr/Salut#9]
Hi, I'm looking for a way to uniquely identify a device. The only thing I've found that should be (as far as I understand) unique inside SalutDevice is macAddress, but it has a protected access rights, so I can't really use it in my classes. So how can I identify a specific device?

**Comment by neatorobito** [comment]
You could use a very small Unique ID generated using whatever the instance name you have is, and the [Java Standard Library](http://www.javapractices.com/topic/TopicAction.do?Id=56).

[Or you could use this, it's also a great library for doing so.](http://hashids.org/java/)

In either case, you could take the person's user/instance name, convert it to numbers, then convert that to a unique HashID.

Then pass that in here:

 `SalutServiceData serviceData = new SalutServiceData("sas", 50489, userNameUniqueID);`

I hope that helps.

**Comment by s0nerik** [comment]
It makes sense, thanks.

**Comment by neatorobito** [comment]
Awesome! :D

**Comment by Hale-ma** [comment]
Hi, There is a passage about getting you own Mac Address [http://robinhenniges.com/en/android6-get-mac-address-programmatically](url) and it works for me in both Android 5.1 device and Android 6 device.
